version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4

    steps:
      - checkout

      - run: yarn install
      - run: yarn prod-json
      # - run: yarn run lint
      # - run: yarn run test --maxWorkers=1
      # - run: yarn run flow

      - run:
          name: Publish to Expo
          command: |
            ./node_modules/.bin/exp login -u $EXPO_USER -p $EXPO_PASSWORD

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              yarn prod-json
              ./node_modules/.bin/exp publish --release-channel alpha --non-interactive
            elif [ "$CIRCLE_BRANCH" == "alphapub" ]; then
              yarn alpha-json
              ./node_modules/.bin/exp publish --release-channel alpha --non-interactive
            fi
